version: "3"
services:
  proxy:
    image: "nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./localhost.crt:/var/www/certs/localhost.crt
      - ./localhost.key:/var/www/certs/localhost.key
    depends_on:
      - php
  php:
    image: "pradex78/php:8.3"
    volumes:
      - ./php-data/:/var/www/html/
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./php-dev.ini:/usr/local/etc/php/conf.d/php-dev.ini
    depends_on:
      - db
    expose:
      - 80
  node:
    image: "node:lts"
    volumes:
      - ./php-data:/app
    working_dir: /app
  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "test"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_PASSWORD: test

volumes:
  data:
    external: true
